### ISSUE TITLE
The word 'find' breaks it

### ISSUE THREAD

**Issue by zenril** [nullabork/talkbot#13]
==> forever.log <==
ERROR: { Error: 13 INTERNAL: Internal error.
    at Object.exports.createStatusError (/root/discord/talkbot/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 13,
  metadata: Metadata { _internal_repr: {} },
  details: 'Internal error.',
  note: 'Exception occurred in retry method that was not classified as transient' }

==> err.log <==
ERROR: { Error: 13 INTERNAL: Internal error.
    at Object.exports.createStatusError (/root/discord/talkbot/node_modules/grpc/src/common.js:87:15)
    at Object.onReceiveStatus (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:1188:28)
    at InterceptingListener._callNext (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:564:42)
    at InterceptingListener.onReceiveStatus (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:614:8)
    at callback (/root/discord/talkbot/node_modules/grpc/src/client_interceptors.js:841:24)
  code: 13,
  metadata: Metadata { _internal_repr: {} },
  details: 'Internal error.',
  note: 'Exception occurred in retry method that was not classified as transient' }

**Comment by wootosmash** [comment]
This is now fixed. 

Turns out the audioEmoji array was having functions attached to the object by some part of the code. So if you said that function name it'd attempt to include that function and go to crap. 

eg audioEmoji['find'] = function() {...}
