### ISSUE TITLE
Bot wouldnt re-join after server disconnect event

### ISSUE THREAD

**Issue by wootosmash** [nullabork/talkbot#37]
**Describe the bug**
The server shutdown due to a disconnect event. 
The bot left voice came back and then left.

**To Reproduce**
This is difficult to reproduce as it requires the server to send a disconnect event.
Try 'follow and wait'

**Expected behavior**
Bot should be useable

**Screenshots**
N/A

**Additional context**
From the error log:

Error: The connection to the voice channel * has not been initialized yet.
    at handleErrCB (/root/projects/talkbot_beta/app/node_modules/discord.io/lib/index.js:1425:25)
    at DiscordClient.DCP.getAudioContext (/root/projects/talkbot_beta/app/node_modules/discord.io/lib/index.js:1390:42)
    at Immediate.botStuff.tts.synthesizeSpeech (/root/projects/talkbot_beta/app/src/models/Server.js:394:13)
    at runCallback (timers.js:803:39)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

**Comment by wootosmash** [comment]
Possibly some progress in this area, we'll see

**Comment by wootosmash** [comment]
I think this has been resolved with some hacking around of the functions
